// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTB_rUtw-rFOpB4BNncnBMpmVOYF8vJNI',
    appId: '1:973165371005:web:a57258f062eb2100351b14',
    messagingSenderId: '973165371005',
    projectId: 'music-diary-50e62',
    authDomain: 'music-diary-50e62.firebaseapp.com',
    storageBucket: 'music-diary-50e62.firebasestorage.app',
    measurementId: 'G-J1HMES96FQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2uN74jnBI5y7FlctmIY-VQsBzwW0H2ek',
    appId: '1:973165371005:android:e577f2c5feb96e51351b14',
    messagingSenderId: '973165371005',
    projectId: 'music-diary-50e62',
    storageBucket: 'music-diary-50e62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4EjiHtQkBHjrVOpVc6u7AUWwxrKtjDgo',
    appId: '1:973165371005:ios:370ecd642d544cc3351b14',
    messagingSenderId: '973165371005',
    projectId: 'music-diary-50e62',
    storageBucket: 'music-diary-50e62.firebasestorage.app',
    iosBundleId: 'com.example.musicDiaryNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4EjiHtQkBHjrVOpVc6u7AUWwxrKtjDgo',
    appId: '1:973165371005:ios:370ecd642d544cc3351b14',
    messagingSenderId: '973165371005',
    projectId: 'music-diary-50e62',
    storageBucket: 'music-diary-50e62.firebasestorage.app',
    iosBundleId: 'com.example.musicDiaryNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTB_rUtw-rFOpB4BNncnBMpmVOYF8vJNI',
    appId: '1:973165371005:web:0752d16d991e52f3351b14',
    messagingSenderId: '973165371005',
    projectId: 'music-diary-50e62',
    authDomain: 'music-diary-50e62.firebaseapp.com',
    storageBucket: 'music-diary-50e62.firebasestorage.app',
    measurementId: 'G-9BLNXE7CBH',
  );

}